[package]
name = "synkronizer"
version = "1.0.0"
edition = "2021"
authors = ["Andri Reveli <reveliandri@gmail.com>"]
description = "Like GNU Stow but written in Rust."
readme = "README.org"
repository = "https://gitlab.com/mercur3/synkronizer"
license-file = "LICENSE"
