[package]
name = "synkronizer"
version = "0.1.0"
edition = "2018"
authors = ["Andri Reveli <reveliandri@gmail.com>"]
description = "Like GNU Stow but written in Rust."
readme = "README.org"
repository = "https://github.com/andri-reveli/synkronizer"
license-file = "LICENSE"
